language: c

sudo: false

matrix: 
  include: 
    - env:
      - CONDA_DEPENDENCIES="pytest pytest-cov numpy astropy"
      - PIP_DEPENDENCIES="codecov"
      - PYTHON_VERSION=2.7
    - env: 
      - CONDA_DEPENDENCIES="pytest pytest-cov numpy astropy"
      - PIP_DEPENDENCIES="codecov"
      - PYTHON_VERSION=3.5
    - env:
      - CONDA_DEPENDENCIES="pytest pytest-cov numpy astropy"
      - PIP_DEPENDENCIES="codecov"
      - PYTHON_VERSION=3.6
    - arch: arm64
      env:
      - CONDA_DEPENDENCIES="pytest pytest-cov numpy astropy"
      - PIP_DEPENDENCIES="codecov"
      - PYTHON_VERSION=3.6
      install: 
      - source setup_conda_arm64.sh
      - conda remove pytest-arraydiff --force || true
      - pip install --user -e .
    - arch: arm64
      env:
      - CONDA_DEPENDENCIES="pytest pytest-cov numpy astropy"
      - PIP_DEPENDENCIES="codecov"
      - PYTHON_VERSION=3.5
    - arch: arm64
      env:
      - CONDA_DEPENDENCIES="pytest pytest-cov numpy astropy"
      - PIP_DEPENDENCIES="codecov"
      - PYTHON_VERSION=2.7
      install: 
      - source setup_conda_arm64.sh
      - conda remove pytest-arraydiff --force || true
      - pip install --user -e .
install:
    - git clone git://github.com/mohneesh9797-puresoftware/ci-helpers
    - source ci-helpers/travis/setup_conda.sh

    # Make sure pytest-arraydiff wasn't installed by conda
    - conda remove pytest-arraydiff --force || true

    # Need to use develop instead of install to make sure coverage works
    - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
         sudo rm /usr/bin/lsb_release;
         pip install --user cython;
         pip install --user numpy;
         pip install --user -e .;
      else 
         pip install -e .;
      fi

script:
   - python -c 'import pytest_arraydiff.plugin'
   - pytest -vv --arraydiff --cov pytest_arraydiff tests
   - pytest -vv --cov pytest_arraydiff --cov-append tests
   - python setup.py check --restructuredtext
   

after_success:
   - codecov
